#  simple travis ci file
language: python

python:
  - "3.5"
  - "3.6"

before_install:
   - pip install -U pip
   - pip install git+git://github.com/ctomkow/pwned
   - pip install codecov

install:

script:
   - py.test --cov=pwned.py tests/

after_success:
  - codecov